version: 2
project_name: newt

release:
  draft: true
  prerelease: "{{ contains .Tag \"-rc.\" }}"
  name_template: "{{ .Tag }}"

builds:
  - id: newt
    main: ./main.go
    binary: newt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.newtVersion={{ .Tag }}

archives:
  - id: binaries
    builds:
      - newt
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: packages
    package_name: newt
    builds:
      - newt
    vendor: fosrl
    maintainer: fosrl <repo@fosrl.io>
    description: Newt - userspace tunnel client and TCP/UDP proxy
    license: AGPL-3.0-or-later
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    file_name_template: "newt_{{ .Version }}_{{ .Arch }}"
    contents:
      - src: LICENSE
        dst: /usr/share/doc/newt/LICENSE
