services:
  collector:
    image: otel/opentelemetry-collector:0.111.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./examples/otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC in
      - "8889:8889"   # Prometheus scrape out

  newt:
    build: .
    image: newt:dev
    environment:
      OTEL_SERVICE_NAME: newt
      NEWT_METRICS_PROMETHEUS_ENABLED: "true"
      NEWT_METRICS_OTLP_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "collector:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
      NEWT_ADMIN_ADDR: "0.0.0.0:2112"
    ports:
      - "2112:2112"
    depends_on:
      - collector

  prometheus:
    image: prom/prometheus:v2.55.0
    volumes:
      - ./examples/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

