global:
  scrape_interval: 15s

scrape_configs:
  # WICHTIG: Newt NICHT direkt scrapen, nur den Collector!
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

    # optional: Kardinalität begrenzen
    relabel_configs:
      - action: labeldrop
        regex: 'tunnel_id'
      # - action: keep
      #   source_labels: [site_id]
      #   regex: '(site-a|site-b)'
