global:
  scrape_interval: 15s

scrape_configs:
  - job_name: newt
    static_configs:
      - targets: ["newt:2112"]
  - job_name: otel-collector
    static_configs:
      - targets: ["collector:8889"]

